### PR TITLE
Document that the installation process should be reproducible

### PR DESCRIPTION
**Pull request by traversaro**
Comments and feedback are welcome!

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Maybe it is worth providing examples on how to do the things mentioned?

**Comment by traversaro** [comment]
> Maybe it is worth providing examples on how to do the things mentioned?

Good point, even if I can probably start a new document for that, and link from there.

**Comment by traversaro** [comment]
I forgot that I opened a related issue in https://github.com/ami-iit/paper_surname_YEAR_journal_short-paper-name/issues/2, but I guess this will close it.

**Comment by traversaro** [comment]
> > Maybe it is worth providing examples on how to do the things mentioned?
> 
> Good point, even if I can probably start a new document for that, and link from there.

Done. The documentation is far from perfect, at least in the conda/mamba case you can actually achieve much higher reproducibility by using stuff as conda-lock or similar, but for sure it is better than nothing.

**Review by S-Dafarra — APPROVED** [review]
Great!

**Pull request merged**
